export const TOGGLE_ASIDE_OPEN="TOOGLE_ASIDE_OPEN";
export const MIDDLE_GROUP_OPEN="MIDDLE_GROUP_OPEN";
export const MIDDLE_GROUP_CLOSE="MIDDLE_GROUP_CLOSE";
export const SMALL_GROUP_OPEN="SMALL_GROUP_OPEN";
export const SMALL_GROUP_CLOSE="SMALL_GROUP_CLOSE";
export const SENIOR_GROUP_OPEN="SENIOR_GROUP_OPEN";
export const SENIOR_GROUP_CLOSE="SENIOR_GROUP_CLOSE";
export const TOGGLE_OPEN_MENU="TOGGLE_OPEN_MENU";

export const SHOW_PHOTOS_PAGE="SHOW_PHOTOS_PAGE";
export const SHOW_VIDEOS_PAGE="SHOW_VIDEOS_PAGE";
export const IMG_OPEN="IMG_OPEN";
export const MODAL_CLOSE="MODAL_CLOSE";
export const NEXT_IMAGE="NEXT_IMAGE";
export const PREV_IMAGE="PREV_IMAGE";



